"use client"

import { useMemo } from "react"
import { useResearchState } from "@/hooks/useResearchState"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Separator } from "@/components/ui/separator"
import { FileText } from "lucide-react"

interface Citation {
  id: number
  title: string
  url?: string
  evidenceGrade: string
  section: string
}

export function PaperView() {
  const sections = useResearchState((s) => s.reportSections)
  const findings = useResearchState((s) => s.findings)
  const status = useResearchState((s) => s.status)

  // Build a deduplicated, numbered reference list from all citations across sections
  const { numberedSections, references } = useMemo(() => {
    const refMap = new Map<string, Citation>()
    let refCounter = 0

    // First pass: collect all unique citations and assign numbers
    for (const section of sections) {
      for (const cite of section.citations) {
        const key = cite.title.toLowerCase().trim()
        if (!refMap.has(key)) {
          refCounter++
          refMap.set(key, {
            id: refCounter,
            title: cite.title,
            url: cite.url,
            evidenceGrade: cite.evidenceGrade,
            section: section.sectionName,
          })
        }
      }
    }

    // Also add findings as references if they have source URLs
    for (const f of findings) {
      const key = f.title.toLowerCase().trim()
      if (!refMap.has(key)) {
        refCounter++
        refMap.set(key, {
          id: refCounter,
          title: f.title,
          url: f.sourceUrl,
          evidenceGrade: f.evidenceGrade,
          section: f.source,
        })
      }
    }

    const refs = Array.from(refMap.values()).sort((a, b) => a.id - b.id)

    // Second pass: inject inline citation numbers [1] into section content
    const processed = sections.map((section) => {
      let content = section.content
      const sectionRefs: number[] = []

      for (const cite of section.citations) {
        const key = cite.title.toLowerCase().trim()
        const ref = refMap.get(key)
        if (ref) {
          sectionRefs.push(ref.id)
        }
      }

      return {
        ...section,
        processedContent: content,
        refNumbers: [...new Set(sectionRefs)].sort((a, b) => a - b),
      }
    })

    return { numberedSections: processed, references: refs }
  }, [sections, findings])

  if (sections.length === 0) {
    if (status === "writing") {
      return (
        <div className="flex h-full items-center justify-center p-4">
          <div className="text-center">
            <FileText className="mx-auto mb-2 h-8 w-8 animate-pulse text-muted-foreground" />
            <p className="text-sm text-muted-foreground">Generating paper...</p>
          </div>
        </div>
      )
    }
    return null
  }

  const overviewSections = numberedSections.filter((s) => s.domain === "overview")
  const bodySections = numberedSections.filter(
    (s) => s.domain !== "overview" && s.domain !== "methodology"
  )
  const methodSections = numberedSections.filter((s) => s.domain === "methodology")

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  return (
    <ScrollArea className="h-full">
      <div className="mx-auto max-w-[640px] px-6 py-10 font-serif">
        {/* ===== Title Block ===== */}
        <div className="mb-8 text-center">
          <h1 className="mb-3 text-2xl font-bold leading-tight">
            Personalized Evidence-Based Research Report
          </h1>
          <p className="text-sm text-muted-foreground">
            Generated by Personal PI &mdash; AI-Powered Research System
          </p>
          <p className="mt-1 text-xs text-muted-foreground">{today}</p>
        </div>

        <Separator className="mb-8" />

        {/* ===== Abstract ===== */}
        {overviewSections.length > 0 && (
          <div className="mb-8">
            <h2 className="mb-3 text-center text-sm font-bold uppercase tracking-widest">
              Abstract
            </h2>
            <div className="rounded-none border-l-2 border-r-2 border-muted px-4">
              {overviewSections.map((s, i) => (
                <div key={i}>
                  {s.processedContent.split("\n").map((para, j) =>
                    para.trim() ? (
                      <p key={j} className="mb-2 text-sm leading-relaxed text-justify">
                        {para}
                        {j === 0 && s.refNumbers.length > 0 && (
                          <InlineCitations nums={s.refNumbers} />
                        )}
                      </p>
                    ) : null
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ===== Body Sections ===== */}
        {bodySections.map((section, idx) => (
          <div key={idx} className="mb-8">
            <h2 className="mb-3 text-base font-bold">
              {idx + 1}. {section.sectionName}
            </h2>
            {section.processedContent.split("\n").map((para, j) =>
              para.trim() ? (
                <p key={j} className="mb-3 text-sm leading-[1.8] text-justify indent-6 first:indent-0">
                  {para}
                </p>
              ) : null
            )}
            {section.refNumbers.length > 0 && (
              <p className="mt-1 text-xs text-muted-foreground">
                <InlineCitations nums={section.refNumbers} />
              </p>
            )}
          </div>
        ))}

        {/* ===== Methodology ===== */}
        {methodSections.length > 0 && (
          <div className="mb-8">
            <h2 className="mb-3 text-base font-bold">
              {bodySections.length + 1}. Methodology
            </h2>
            {methodSections.map((section, i) => (
              <div key={i}>
                {section.processedContent.split("\n").map((para, j) =>
                  para.trim() ? (
                    <p key={j} className="mb-3 text-sm leading-[1.8] text-justify">
                      {para}
                    </p>
                  ) : null
                )}
              </div>
            ))}
            {/* Auto methodology */}
            <div className="mt-2 text-sm leading-[1.8]">
              <p className="mb-2">
                <strong>Databases searched:</strong>{" "}
                {[...new Set(findings.map((f) => f.sourceType))]
                  .map((t) =>
                    t === "pubmed"
                      ? "PubMed/MEDLINE"
                      : t === "exa"
                        ? "Exa AI (web)"
                        : t === "onet"
                          ? "O*NET OnLine"
                          : t.toUpperCase()
                  )
                  .join(", ")}
              </p>
              <p className="mb-2">
                <strong>Sources reviewed:</strong> {findings.length} primary sources were identified,
                screened for relevance, and graded for evidence quality using the Personal PI
                evidence grading framework (A&ndash;F scale).
              </p>
              <p>
                <strong>Inclusion criteria:</strong> Peer-reviewed publications, published within the
                last 10 years (preferred), with sample populations applicable to the subject&apos;s
                demographic profile.
              </p>
            </div>
          </div>
        )}

        {/* If no explicit methodology section, still show auto one */}
        {methodSections.length === 0 && (
          <div className="mb-8">
            <h2 className="mb-3 text-base font-bold">
              {bodySections.length + 1}. Methodology
            </h2>
            <div className="text-sm leading-[1.8]">
              <p className="mb-2">
                This report was generated using a multi-agent AI research system that conducted
                parallel searches across multiple databases. Each finding was independently graded
                for evidence quality.
              </p>
              <p className="mb-2">
                <strong>Databases searched:</strong>{" "}
                {[...new Set(findings.map((f) => f.sourceType))]
                  .map((t) =>
                    t === "pubmed"
                      ? "PubMed/MEDLINE"
                      : t === "exa"
                        ? "Exa AI (web)"
                        : t === "onet"
                          ? "O*NET OnLine"
                          : t.toUpperCase()
                  )
                  .join(", ")}
              </p>
              <p className="mb-2">
                <strong>Sources reviewed:</strong> {findings.length}
              </p>
              <p>
                <strong>Evidence grading:</strong> A (meta-analysis/systematic review), B (multiple
                RCTs), C (single RCT/strong observational), D (preliminary/limited), F (expert
                consensus only).
              </p>
            </div>
          </div>
        )}

        <Separator className="mb-8" />

        {/* ===== References ===== */}
        <div className="mb-12">
          <h2 className="mb-4 text-center text-sm font-bold uppercase tracking-widest">
            References
          </h2>
          <ol className="list-none space-y-3">
            {references.map((ref) => (
              <li key={ref.id} className="flex gap-2 text-xs leading-relaxed">
                <span className="shrink-0 font-mono text-muted-foreground">[{ref.id}]</span>
                <span>
                  {ref.title}
                  {ref.url && (
                    <>
                      {" "}
                      <a
                        href={ref.url.startsWith("http") ? ref.url : `https://pubmed.ncbi.nlm.nih.gov/${ref.url.replace("PMID:", "")}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 hover:underline dark:text-blue-400"
                      >
                        {ref.url}
                      </a>
                    </>
                  )}
                  <span className="ml-1 text-muted-foreground">
                    [Evidence Grade: {ref.evidenceGrade}]
                  </span>
                </span>
              </li>
            ))}
          </ol>
        </div>

        {/* ===== Footer ===== */}
        <Separator className="mb-4" />
        <p className="text-center text-[10px] text-muted-foreground">
          This report was generated by Personal PI, an AI-powered personalized research system.
          All claims are graded for evidence quality. This report is not medical or professional advice.
          Consult qualified professionals before making health or career decisions.
        </p>
      </div>
    </ScrollArea>
  )
}

function InlineCitations({ nums }: { nums: number[] }) {
  return (
    <sup className="ml-0.5 font-sans text-[9px] font-medium text-blue-600 dark:text-blue-400">
      [{nums.join(", ")}]
    </sup>
  )
}

/** Export the paper as plain text with numbered references */
export function paperToText(
  sections: import("@/lib/types").ReportSection[],
  findings: import("@/lib/types").Finding[]
): string {
  const lines: string[] = []

  lines.push("PERSONALIZED EVIDENCE-BASED RESEARCH REPORT")
  lines.push(`Generated by Personal PI — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`)
  lines.push("")
  lines.push("=" .repeat(60))
  lines.push("")

  // Build reference map
  const refMap = new Map<string, { id: number; title: string; url?: string; grade: string }>()
  let refCounter = 0
  for (const section of sections) {
    for (const cite of section.citations) {
      const key = cite.title.toLowerCase().trim()
      if (!refMap.has(key)) {
        refCounter++
        refMap.set(key, { id: refCounter, title: cite.title, url: cite.url, grade: cite.evidenceGrade })
      }
    }
  }
  for (const f of findings) {
    const key = f.title.toLowerCase().trim()
    if (!refMap.has(key)) {
      refCounter++
      refMap.set(key, { id: refCounter, title: f.title, url: f.sourceUrl, grade: f.evidenceGrade })
    }
  }

  const overviewSections = sections.filter((s) => s.domain === "overview")
  const bodySections = sections.filter((s) => s.domain !== "overview" && s.domain !== "methodology")

  // Abstract
  if (overviewSections.length > 0) {
    lines.push("ABSTRACT")
    lines.push("-".repeat(40))
    for (const s of overviewSections) {
      lines.push(s.content)
      const refs = s.citations
        .map((c) => refMap.get(c.title.toLowerCase().trim())?.id)
        .filter(Boolean)
      if (refs.length > 0) lines.push(`[${refs.join(", ")}]`)
    }
    lines.push("")
  }

  // Body
  bodySections.forEach((s, i) => {
    lines.push(`${i + 1}. ${s.sectionName.toUpperCase()}`)
    lines.push("-".repeat(40))
    lines.push(s.content)
    const refs = s.citations
      .map((c) => refMap.get(c.title.toLowerCase().trim())?.id)
      .filter(Boolean)
    if (refs.length > 0) lines.push(`[${refs.join(", ")}]`)
    lines.push("")
  })

  // Methodology
  lines.push(`${bodySections.length + 1}. METHODOLOGY`)
  lines.push("-".repeat(40))
  lines.push(`Databases searched: ${[...new Set(findings.map((f) => f.sourceType))].join(", ")}`)
  lines.push(`Sources reviewed: ${findings.length}`)
  lines.push(`Evidence grading: A (meta-analysis), B (multiple RCTs), C (single RCT), D (preliminary), F (expert consensus)`)
  lines.push("")

  // References
  lines.push("=" .repeat(60))
  lines.push("REFERENCES")
  lines.push("=" .repeat(60))
  const refs = Array.from(refMap.values()).sort((a, b) => a.id - b.id)
  for (const ref of refs) {
    lines.push(`[${ref.id}] ${ref.title}${ref.url ? ` — ${ref.url}` : ""} [Grade: ${ref.grade}]`)
  }

  lines.push("")
  lines.push("---")
  lines.push("Generated by Personal PI. Not medical or professional advice.")

  return lines.join("\n")
}
